### PR TITLE
Add support for Django 3.2

### PR DESCRIPTION
**Pull request by dzen**

### CODE REVIEW

**Comment by Natureshadow** [comment]
Is this a change necessary for compatibility with Django 3.2?

**Comment by dzen** [comment]
Two things I noted : 
- I think the `attname`attribute seems to be removed, I did not find any reference for the moment
- It seems there are some SQL improvements which breaks the sql regex in https://github.com/django-ldapdb/django-ldapdb/blob/ef843d610c1d85b0ecbe67553ee733a4fd03c16c/ldapdb/backends/ldap/compiler.py#L17

I'm trying to fix the second point.

The commits are not very clean for the moment, I wanted to trigger a travis build.

**Comment by dzen** [comment]
Hello @Natureshadow,

I can update the commit to make it more clean.
There are failing test because of the CI, not because of the code.

**Comment by Natureshadow** [comment]
> There are failing test because of the CI, not because of the code.

While this might be true for the one pipeline failing because of missing build dependencies, but not for those failing in Django 2.2.

**Comment by dzen** [comment]
hi @Natureshadow I updated the test and cleaned the commit.

Hope You'll have a few times to review it.

Thanks

**Comment by Natureshadow** [comment]
Looks good. Any objections, @rbarrois ?

**Comment by dzen** [comment]
any news on this ? :)

With a new release, we will include the database router improvements too.

Thanks

**Comment by Natureshadow** [comment]
I will merge if @rbarrois does not object today.

**Pull request merged**
