### PR TITLE
Actually register gte and lte lookups for DateField.

### PR DESCRIPTION
**Pull request by Natureshadow**

### CODE REVIEW

**Comment by Natureshadow** [comment]
Merged in my fork at https://edugit.org/nik/django-ldapdb2 (also in django-ldapdb2 on PyPI).

**Comment by ikreb7** [comment]
Thank you for your pull request. If you add tests for it I will merge it.

**Comment by Natureshadow** [comment]
Haha, that one was good :D. Wasn't it you who oversaw the missing registration for ages because he didn't write tests in the first place ;)?

So no, I'll leave that to you.

**Comment by romain-dartigues** [comment]
@Natureshadow Thank you, but I have a question (related to #149).

After applying your patch, the query does not fail anymore, but the date format used for the query is invalid (at least with my schema on my OpenLDAP server) :
```python
>>> ldapdb.backends.ldap.compiler.query_as_ldap(qs.query, compiler, connection)
LdapLookup(base='ou=people,dc=example,dc=net', scope=2, filterstr='(&(objectClass=posixAccount)(pwdChangedTime<=2018-01-01))')
```

Should not it be `20180101000000Z` instead of `2018-01-01`?
* https://docs.oracle.com/cd/E19450-01/820-6173/def-greater-than-or-equal-search-filter.html
* https://en.wikipedia.org/wiki/GeneralizedTime
* https://tools.ietf.org/html/rfc4517#section-3.3.13

**Comment by rbarrois** [comment]
Hi,

Thanks for the contribution!
I've taken a thorough look at the RFCs, and implemented these lookups in a new DateTimeField — See f497e76d7a07462eebab55c23723073dcf037f47.

**Pull request closed without merging**
