### PR TITLE
Fix #62: Python 3 Support

### LINKED ISSUE #62: Python 3 Support
Do you plan to support Python 3 in the future?
This will be a really nice feature!

### PR DESCRIPTION
**Pull request by midnightlynx**
Updates to make code compatible with Python 3

### CODE REVIEW

**Comment by charlesfg** [comment]
Hello,  can we help on test and validation in some way?

We would clone the @midnightlynx develop branch and use it on our project!
@jlaine if there's something that we could do to make this PR accepted, just ask!

**Comment by higoramp** [comment]
hello @midnightlynx ...

We've bump into   “expected a string in the list” error in your code and needed to change the models/base.py line 110 to:
```python
                if value:
                    value[:] = [x.encode(charset) for x in value]
                    entry.append((field.db_column, value))
```
Can you have a look to check if there's anything going wrong in our change?

**Comment by midnightlynx** [comment]
@higoramp:

That change doesn't look like things would break, but it would be better to do in the field's `get_db_prep_save` method.
I thought I got those all fixed up, actually. Do you know which field type or types gives that error?

**Comment by midnightlynx** [comment]
I'm reviewing the encoding/decoding on all the fields, and attempting a fix.
Work in progress.

**Comment by midnightlynx** [comment]
@higoramp 

Should be good without your change now. Thanks for spotting that.

**Comment by rbarrois** [comment]
Hello there, I think this has all been merged in the 0.5.0 release?

Let me know if it isn't the case ;)

**Pull request closed without merging**
