### PR TITLE
Python 2 requires str objects in setup.py, not unicode ones.

### PR DESCRIPTION
**Pull request by d9pouces**
In Python 2, some tools crash when the values are represented by unicode objects instead of str (like bdist_stdeb, for generating .deb packages).

### CODE REVIEW

**Comment by rbarrois** [comment]
Hello,

Sorry for being late :/

I'd rather fix either the tools or the specific fields, instead of having inconsistent types between py2 and py3.

Would you have an example of a stacktrace of such tools?

Thanks!

**Comment by rbarrois** [comment]
@d9pouces Are the new commits related to the pull request?

I'm getting lots of notifications ;)

Thanks!

**Comment by d9pouces** [comment]
Bonjour,

je me permets de passer en français, c’est plus simple :-)
J’avais oublié cette pull request, je pense d’ailleurs la supprimer vu que j’ai fait l’erreur de la faire avec ma branche master et qu'elle n’a plus lieu d’être en Python 3.

J’aimerais apporter la possibilité de faire de l'authent’ SASL avec django-ldapdb afin d’utiliser gssapi ou external, vu que pyldap le prévoit. Du coup, une nouvelle pull request est à prévoir ^^

Désolé pour toutes les notifications !

Mathieu

**Comment by ikreb7** [comment]
Hello @d9pouces, i translated your message with google translator.

Hello, I allow myself to pass in French, it's simpler :-) I forgot this pull request, I think also remove it since I made the mistake of doing it with my branch master and that it no longer needs to be in Python 3. I would like to provide the opportunity to authenticate SASL with django-ldapdb in order to use gssapi or external, as pyldap foresees. So, a new pull request is expected ^^ Sorry for all notifications! Mathieu

If I understand you corectly I could close this pull request, do I? 

If you want sasl support for django-ldapdb, I am happy if you make a new pull request.

**Pull request closed without merging**
