### PR TITLE
Update to Django 3

### PR DESCRIPTION
**Pull request by SuperMeepBoy**
Tentative de passer django-ldapdb à Django 3.

### CODE REVIEW

**Comment by dzen** [comment]
Django 3 is released since 9 month, it's probably time to add a proper support.

1. a few modifications to django new path() functions instead of urls()
2. correctly configure the example settings according to the new TEMPLATES context processor requirements
3. the database operation class has a new `sql_flush` signature.

This PR is just here to discuss how to do it properly.

What do you have in mind ? handling multiple function signature might not be handy

**Comment by rbarrois** [comment]
I thinki the following should work:

```python
if django.VERSION[0] <= 2:
    def sql_flush(self, style, tables, sequences, allow_cascade=False):
        ...
else:
    def sql_flush(self, style, tables, *, reset_sequences=False, allow_cascade=False):
        ...
```

Since the functions' bodies are small, there is little code duplication.

**Comment by dzen** [comment]
hi @rbarrois,

Tests fails on django 1.11, but it's probably a good time to drop support for this version ?

**Comment by rbarrois** [comment]
And it's merged (manually)! Thanks for the help :)

**Pull request closed without merging**
