### PR TITLE
Make it possible to change objects found deeper than model's base_dn

### PR DESCRIPTION
**Pull request by g1itch**
This solves #3 for me.

### CODE REVIEW

**Comment by Natureshadow** [comment]
Can we update this merge request to only reflect the implemented bugfix (no whitespace or other changes), then merge it ☺?

**Comment by Natureshadow** [comment]
Also: Shouldn't this somehow use the `scoped` method? Like, verify the object has the same base DN as the class, and if not, turn it into a scoped version with the other base DN? I am not entirely sure, but I think that's what the scoping is for.

**Comment by Natureshadow** [comment]
@g1itch Any feedback ☺?

**Comment by g1itch** [comment]
OK, I dropped flake8 commit. Maybe this should use `scoped()`, I don't know. But when I wrote this changes that method didn't fit my needs for some reason. It was too long ago.

**Comment by Natureshadow** [comment]
OK, thanks!

In baruser, you used the wrong base DN (dc=nodomain instead of dc=example,dc=org). Please fix this. After that, I will merge.

**Comment by g1itch** [comment]
Thank you for the tip. Now I cannot even run tests locally because I still have django-1.7 on my working PC.

**Comment by Natureshadow** [comment]
Thanks for your contribution!

**Pull request merged**
