### PR TITLE
MultiValueField

### PR DESCRIPTION
**Pull request by peppelinux**
First time using this awesome application, thank you for writing this.
Using ListField with Django 2 experienced to me this issue:

https://github.com/django-ldapdb/django-ldapdb/issues/151

I created another Field as my purpose for LDAP MultiValue fileds, instead of raw list representation.

I also included a js called textarea-autosize.js to have a better TextArea representation.
Hope you'll enjoy as I enjoyed writing this in django-ldapdb. 

screenshot at 2018-07-06 20 32 57

### CODE REVIEW

**Comment by Natureshadow** [comment]
Your PR mixes a lot of stuff. I think you might want to separate it into logical units.

**Comment by peppelinux** [comment]
I have to separate code into separate branches, I didn't know that a PR would take so much time.
I Will, first of all I need to know if MultiValueField is really needed and if @rbarrois is interested in it, otherwise it could be a waste of time

**Comment by peppelinux** [comment]
bytheway @Natureshadow if you want to try it you should only merge this diff:
https://github.com/django-ldapdb/django-ldapdb/pull/152/files#diff-d0121656a61c2e93579fcf4c8dfc0e40

**Comment by Natureshadow** [comment]
I still do not hink this is a good idea.

This will break, if only then,  the moment a multi-value field cotains a newline (which is perfectly valid).

What is the improvement compared to ListField?

**Comment by peppelinux** [comment]
I used MultiValueField to avoid numb newline char. If you think that a newline dhoud be stored I'll move this feature to a personal branch and close this PR. At the moment my production data doesnt allow newline.

New approches are also appreciated.
I use multivalue field for better navigation in modeladmn, we could also use ListField and managing its style through modeladmin form.

I coded it also to patch some bugs that at that moment was not fixed, but I saw a lot of commits during these last days

**Comment by Natureshadow** [comment]
Well, it is not so much about whether I think newlines should be stored - it's about newlines being an entirely acceptable character in an entry of an LDAP attribute. Notice how your approach breaks that data even when loading and saving an obejct without even messing with the MultiValueField - the way your code works, just loasing and saving as is would tear apart such fields, breaking data without the user even touching it.

I see how the ModelAdmin can be improved for the ListField, though.

**Comment by Natureshadow** [comment]
The issue with encoding in the ListField was fixed, yes ☺.

I propose we work on another PR to just introduce the admin improvements on top of ListField. I do however think this is not very specific to django-ldapdb, even thoug hthe notion of such a field type does not exist elsewhere.

**Comment by peppelinux** [comment]
Good news, I'll introduce ListField and then a PR for such modeladmin form. So this should be closed, thank ypu for your attenction, I appreciate

**Pull request closed without merging**
