### PR TITLE
Use ReconnectLDAPObject to survive temporary LDAP issues (See #80, #112)

### PR DESCRIPTION
**Pull request by pdpotter**
Pull request from a clean branch (See #112).

### CODE REVIEW

**Comment by rbarrois** [comment]
Thanks for the input!
That's indeed an issue we need to address.

However, I've got two questions regarding the proposed change:
* From what I see in the Django source code, the connection should be established in [``get_new_connection()``](https://github.com/django/django/blob/master/django/db/backends/base/base.py#L160), which is wrapped by [``ensure_connection()``](https://github.com/django/django/blob/master/django/db/backends/base/base.py#L207)/[``connect()``](https://github.com/django/django/blob/master/django/db/backends/base/base.py#L174); did you encounter an issue with that behaviour?
* Django already has some mechanisms to deal with unusable connections, notably the [``is_usable``](https://github.com/django/django/blob/master/django/db/backends/base/base.py#L490) flag; shouldn't we implement that function instead?

**Comment by pdpotter** [comment]
Thanks for the review!

* The code in [5349a55](https://github.com/django-ldapdb/django-ldapdb/pull/113/commits/5349a554048f4de3bdd755c4d17ccda7c6b529cd) was copied from a patch applied before [Properly use Django's database backend API.](https://github.com/django-ldapdb/django-ldapdb/commit/068b851085c9caf1bd18e4aaf34307b0d63d9257). There is no issue with `ensure_connection()` / `connect()`, I fixed this in [2c2235b](https://github.com/django-ldapdb/django-ldapdb/pull/113/commits/2c2235b6012d6494ef01cd2ad3393c2577ae73e1).
* According to [this comment](https://code.djangoproject.com/ticket/26282#comment:1), the usage of `connection.ensure_connection()` is encuraged over the usage of `is_usable()`

**Comment by rbarrois** [comment]
Thanks!

I'll try to merge this for the next minor release (0.9).

**Comment by peppelinux** [comment]
Good feature! Great

**Pull request merged**
