### PR TITLE
Actually register gte and lte lookups for DateField

### PR DESCRIPTION
**Pull request by romain-dartigues**
Same same as #130 but with minimal unit tests to allow a merge.

I still need your input, because, in my setup, dates are *not* stored in ISO 8601 extended format.

I think the format used in the search filter should, at least, use the date representation set in the field format (in my case it is `%Y%m%d%H%M%SZ`).

I'm quite allergic to the LDAP format, so your enlightenment will be welcome, but what I [could](https://stackoverflow.com/a/18632573) [find](https://docs.oracle.com/cd/E19450-01/820-6173/def-greater-than-or-equal-search-filter.html) [around](http://www.openldap.org/lists/openldap-software/200603/msg00330.html) seems to point that the filter should be in [generalized time](https://tools.ietf.org/html/rfc4517#section-3.3.13):

> The LDAP-specific encoding of a value of this syntax is a restriction of the format defined in ISO8601

### CODE REVIEW

**Comment by romain-dartigues** [comment]
I might be easier to maintain only one field; but for consistency with the [Django models](https://docs.djangoproject.com/en/2.0/ref/models/fields/) I think both of them should be exposed.

**Comment by rbarrois** [comment]
OK, this is going to take some more time: some schemas (e.g nis.schema) encode a few attributes as UNIX timestamps; we'd want those to be handled by a DateTimeField too...

**Comment by peppelinux** [comment]
In my slapd setup I have only timestamps and timestamps with millisecond when returns from pwdFailureTime.

This is an example code I use to parse these.

````
import time
from datetime import datetime
from django.utils import timezone

from django.conf import settings

LDAP_DATETIME_FORMAT = '%Y%m%d%H%M%SZ'
LDAP_DATETIME_MILLISECONDS_FORMAT = '%Y%m%d%H%M%S.%fZ'

def parse_time(timestr, tformat):
    time_struct = time.strptime(timestr, tformat)
    timestamp = time.mktime(time_struct)
    return timezone.get_current_timezone().localize(timezone.datetime.fromtimestamp(timestamp))

def parse_generalized_time(timestr):
    return parse_time(timestr, settings.LDAP_DATETIME_FORMAT)

def parse_pwdfailure_time(timestr):
    return parse_time(timestr, settings.LDAP_DATETIME_MILLISECONDS_FORMAT)
````

Would you like to introduce a specialized field like SlapdDateTimeField?
We could introduce also dateutils for automagic datetime parse but I wouldn't carry too much things on Field Classes. I think that it would be better to know which format returns from a LDAP attribute and use the correct FieldType in model definition.

**Comment by rbarrois** [comment]
OK, I've finally finished those checks — and reread the RFCs.

django-ldapdb now includes a proper DateTimeField, RFC-compliant; and a TimestampField (useful for shadowAccount fields)!

See f497e76d7a07462eebab55c23723073dcf037f47 for details!

**Comment by peppelinux** [comment]
Hi Raphael, thank your for your support and for this commit!

I would like to ask to to not close this issue until these Fields would be included in Official Doc and.
Thus, I would like to ask you to introduce, or accept or purpose some PR, to register also *LtLookup and *GtLookup because these are needed for admin list_filters If you agree.

If this issue must be closed please move the usefull information to another if you agree
thx

**Pull request closed without merging**
